fixup! cicd: change to run on arc-runner-set-latest-image-1
Signed-off-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

diff --git a/.github/workflows/actualunittests.yaml b/.github/workflows/actualunittests.yaml
--- a/.github/workflows/actualunittests.yaml
+++ b/.github/workflows/actualunittests.yaml
@@ -124,4 +124,13 @@ jobs:
       - name: Install package with test dependencies
         run: pip install -e . --no-deps --no-build-isolation -vvv --verbose
       - name: Run unit tests
-        run: pytest tests/ -vvv -s
+        run: |
+          pytest tests/ -vvv -s
+          EXIT_CODE=$?
+          echo "pytest EXIT_CODE: ${EXIT_CODE}"
+          if [[ "$EXIT_CODE" != '0' ]] ; then
+            echo 'pytest fail, sleeping so the user can exec in...'
+            tail -f /dev/null
+          else
+            echo 'pytest success'
+          fi
